### PR TITLE
Use TTF instead of OTF

### PR DESCRIPTION
**Pull request by alexeyten**
OTF package breaks font choosing completely for me. I had to wipe Data. Let's try TTF version

### CODE REVIEW

**Comment by angelsl** [comment]
That's strange. OTF worked for me when I used it.

Alright. Give me a moment.

**Comment by alexeyten** [comment]
Could you give me APK before publishing?

**Comment by angelsl** [comment]
https://mega.co.nz/#!vcpgXJrZ!S-nzNxXezRatHJChvCid5zFmg8sK7wZrfZGBkmxfB7c

**Comment by alexeyten** [comment]
It works! :+1:

Fira Sans

**Pull request merged**
